news-django-client/news/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('stories.urls')),
]

news-django-client/stories/urls.py
from django.conf import settings
from django.urls import path


from stories.views import HomePageView, AddNewsView, ImageView, ShowNewsView, AddUserView
from django.conf.urls.static import static

app_name = 'stories'

urlpatterns = [
    path('', HomePageView.as_view(), name="homepage"),
    path('addnews/', AddNewsView.as_view(), name="addnews"),
    path('shownews/<int:newsid>/', ShowNewsView.as_view(), name="shownews"),
    path('image/<slug:hash>/', ImageView.as_view(), name="image"),
    path('adduser/', AddUserView.as_view(), name="adduser"),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

news-django-client/stories/models.py
from django.db import models

# Create your models here.

news-django-client/stories/forms.py
from django import forms

class AddNewsForm(forms.Form):
    text=forms.CharField(widget=forms.Textarea)
    image=forms.FileField()
    user_id=forms.IntegerField()
    privatekey=forms.IntegerField()
    private_n=forms.IntegerField()

class AddUserForm(forms.Form):
    userid = forms.IntegerField()
    prime1 = forms.IntegerField()
    prime2 = forms.IntegerField()

news-django-client/stories/views.py
from django.http import HttpResponse
from django.shortcuts import render
from django.views import View
from django.conf import settings
from web3 import Web3
import ipfsapi
from tempfile import NamedTemporaryFile
from stories.rsa import generate_keypair, encrypt

from stories.forms import AddNewsForm, AddUserForm

w3 = Web3(Web3.HTTPProvider(settings.RPC_PROVIDER))
contract = w3.eth.contract(abi=settings.CONTRACT_ABI, address=settings.CONTRACT_ADDRESS)
ipfs = ipfsapi.connect(settings.IPFS_SERVER_ADDR, settings.IPFS_SERVER_PORT)

nullstrip = lambda x: x.rstrip('\x00')

def gethash(filepath):
    res = ipfs.add(filepath)
    return (res["Hash"][:24], res["Hash"][24:])

def getfilehash(filehash1,filehash2):
    filehash = zip(filehash1, filehash2)
    filehash = [nullstrip(x[0]) + nullstrip(x[1]) for x in filehash]
    return filehash

# Create your views here.
class HomePageView(View):
    def get(self, request):
        news = contract.call().getNews()
        newstext = list(map(ipfs.cat,getfilehash(news[0], news[1])))
        newsimage = getfilehash(news[2], news[3])
        news=zip(newstext,newsimage)
        news = [{"id":i,"text":x[0].decode('utf-8').partition('\n'),"image":x[1]} for i,x in enumerate(news)]
        return render(request, 'stories/homepage.html', {"news": news})

class ShowNewsView(View):
    def get(self, request, newsid):
        news = contract.call().oneNews(newsid)
        news = list(map(nullstrip, news))
        texthash=news[0]+news[1]
        imagehash=news[2]+news[3]
        text=ipfs.cat(texthash).decode('utf-8').partition('\n')
        return render(request, 'stories/shownews.html', {"title":text[0],"text":text[2], "image":imagehash})

class AddNewsView(View):
    def get(self, request):
        form = AddNewsForm()
        return render(request, 'stories/addnews.html', {"form": form})
    def post(self, request):
        form = AddNewsForm(request.POST, request.FILES)
        if form.is_valid():
            text=form.cleaned_data["text"]
            image=request.FILES["image"]
            privatekey=(form.cleaned_data["privatekey"],form.cleaned_data["private_n"])
            userid=form.cleaned_data['user_id']
            with NamedTemporaryFile("w") as textFile:
                textFile.write(text)
                textFile.flush()
                hash=gethash(textFile.name)
            with NamedTemporaryFile("wb") as imagefile:
                for chunk in image.chunks():
                    imagefile.write(chunk)
                imagefile.flush()
                hash2=gethash(imagefile.name)
            message="abcd"
            cipher=encrypt(privatekey, message)
            message=list(map(ord,message))
            contract.transact({"from":w3.eth.coinbase}).verify(hash[0], hash[1], hash2[0], hash2[1], message,cipher,userid,len(message),privatekey[1])
            return render(request, 'stories/addnews_success.html')
        return render(request, 'stories/addnews.html', {"form": form})

class AddUserView(View):
    def get(self, request):
        form = AddUserForm()
        return render(request, 'stories/adduser.html', {"form": form})
    def post(self, request):
        form = AddUserForm(request.POST)
        if form.is_valid():
            prime1=form.cleaned_data["prime1"]
            prime2=form.cleaned_data["prime2"]
            userid=form.cleaned_data["userid"]
            (privatekey, publickey)=generate_keypair(prime1, prime2)

            contract.transact({"from":w3.eth.coinbase}).createUser(userid, publickey[0])
            return render(request, 'stories/adduser_success.html', {"privatekey":privatekey,"publickey":publickey, "userid":userid})

        return render(request, 'stories/adduser.html', {"form": form})

class ImageView(View):
    def get(self, request, hash):
        imagedata=ipfs.cat(hash)
        return HttpResponse(imagedata, content_type="image/jpeg")

news-django-client/stories/templates/base.html
<!DOCTYPE html>
{% load static %}
<html>
  <title>CryptNews!</title>
  <head>
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'style.css' %}">
  </head>
  <body>
    <h4 class="display-1">CryptNews!</h2>
    <nav class="navbar navbar-expand-sm navbar-dark bg-primary mb-3">
      <div class="container">
        <a class="navbar-brand" href="{% url 'stories:homepage' %}">Latest News</a>
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'stories:homepage' %}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'stories:addnews' %}">Add News</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'stories:adduser' %}">Add User</a>
          </li>
        </ul>
      </div>
    </nav>
    <div class="blog-section paddingTB60 ">
      <div class="container">
        <div class="row">
          <div class="site-heading text-center">
            <h3>Our Portfolio</h3>
            <p><h5>Making news immutable,distributed,reliable and secure</h5></p>
            <div class="border"></div>
          </div>
        </div>
        {% block content %}{% endblock %}
        <br>
      </div>
    </div>
  </body>
</html>

news-django-client/stories/templates/stories/addnews.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}
{% block content %}
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{form|crispy}}
    <button type="submit" class="btn btn-primary">Submit</button>
</form>

{% endblock %}

news-django-client/stories/templates/stories/addnews_success.html
{% extends 'base.html' %}

{% block content %}
<p>A block is added to the blockchain. It will be mined soon.</p>
{% endblock %}

news-django-client/stories/templates/stories/adduser.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}
{% block content %}
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{form|crispy}}
    <button type="submit" class="btn btn-primary">Submit</button>
</form>

{% endblock %}

news-django-client/stories/templates/stories/adduser_success.html
{% extends 'base.html' %}

{% block content %}
<p>Please store this info</p>
<p>User ID: {{userid}}</p>
<p>Private Key: {{ privatekey }}</p>
<p>Public Key: {{ publickey }}</p>
{% endblock %}

news-django-client/stories/templates/stories/homepage.html
{% extends 'base.html' %}

{% block content %}
<div class="row text-center">
  {% for el in news %}
  <div class="col-sm-6 col-mid-4" >
    <div class="blog-box">
      <div class="blog-box-image">
        <img src="{% url 'stories:image' hash=el.image %}" class="img-responsive" alt="">
      </div>
      <div class="blog-box-content">
        <h4><a href="#" >{{ el.text.0 }}</a></h4>
        <p>{{ el.text.1 }}</p>
        <a href="{% url 'stories:shownews' newsid=el.id %}" class="btn btn-default site-btn">READ MORE</a>
      </div>
    </div>
  </div>
  {% endfor %}
</div>
{% endblock %}

news-django-client/stories/templates/stories/shownews.html
{% extends 'base.html' %}

{% block content %}
<div class="row text-center">
      <div class="blog-box-image">
        <img src="{% url 'stories:image' hash=image %}" class="img-responsive" alt="">
      </div>
    <div class="blog-box-content">
      <h1><a href="#" >{{ title }}</a></h1>
      <p>{{ text }}</p>
    </div>
    </div>
{% endblock %}